name: pytest

on:
  push:
    branches: [ master ]
    paths: 
       - daluke/**.py
       - requirements.txt
       - .github/**
       
  pull_request:
    branches: [ master ]
    paths:
       - daluke/**.py
       - requirements.txt
       - .github/**
       
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-cov
          pip install .

      - name: Run test
        run: |
            echo "PYTHONPATH=home/runner/work/daLUKE" >> $GITHUB_ENV
            pytest --cov
