name: pytest

on:
  push:
    branches: [ master ]
#   paths: 
  pull_request:
    branches: [ master ]
#   paths:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        with:
          python-version: 3.8

      - name: Set up dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run test
        run: pytest --cov
